Update README to use via OADP
konveyor/volume-snapshot-mover pull request #121
Opened 2022-07-20 21:35 UTC by eemcmullan

2022-07-20 21:49 UTC, savitharaghunathan requested changes

2022-07-21 03:09 UTC, shubham-pampattiwar requested changes

2022-07-21 03:09 UTC, shubham-pampattiwar commented on README.md
> +- Have an appropriate StorageClass and VolumeShapshotClass:
Can we something regarding the cluster having only one `default` volumesnapshotclass ?

2022-07-21 03:09 UTC, shubham-pampattiwar commented on README.md
> +    dataMoverCredential: <secret-name>
Add a note that if this name is not specified then `dm-credentials` is the default name expected by the controller

2022-07-21 03:09 UTC, shubham-pampattiwar commented on README.md
> +  resticSecretRef: <your-restic-secret>
+1

2022-08-01 15:36 UTC, savitharaghunathan requested changes

2022-08-01 15:36 UTC, savitharaghunathan commented on README.md
> +  - Add the restic secret name from the previous step to your DPA CR in `spec.features.dataMoverCredential`.
`spec.features.dataMoverCredential` -> `spec.features.dataMover.credentialName`

2022-08-01 15:36 UTC, savitharaghunathan commented on README.md
> +  - Note the CSI `defaultPlugin` and `enableDataMover` flag.
enableDataMover -> `spec.features.dataMover.enable`

2022-08-01 15:36 UTC, savitharaghunathan commented on README.md
> +    dataMoverCredential: <secret-name>
Please update this CR to match current API

2022-08-02 18:54 UTC, eemcmullan commented on README.md
> +- Have an appropriate StorageClass and VolumeShapshotClass. **Make sure there is only one default of each.**
Add example vsClass and storageClass

2022-08-03 19:20 UTC, savitharaghunathan approved these changes
/lgtm
Thanks, @eemcmullan

2022-08-03 19:41 UTC, shubham-pampattiwar approved these changes

2022-08-03 19:41 UTC, merged